export { PlatformApiError, PlatformValidationError } from "./errors.js"
export { createKickClient } from "./kick.js"
export { createMultiPlatformClient } from "./multi-platform.js"
export { createTwitchClient } from "./twitch.js"
export { createGoogleYoutubeClient, createYoutubeClient } from "./youtube.js"
export type {
    MultiPlatformYoutubeChannelMetricsRequest,
    MultiPlatformTwitchChannelMetricsRequest,
    MultiPlatformChatListener,
    MultiPlatformChatListenBatchRequest,
    MultiPlatformChatListenRequest,
    MultiPlatformChatStartResult,
    MultiPlatformChatStopOptions,
    MultiPlatformChatWebhookDispatchResult,
    MultiPlatformChatsClient,
    MultiPlatformChannelMetricsBatchRequest,
    MultiPlatformChannelMetricsRequest,
    MultiPlatformChannelResolveRequest,
    MultiPlatformChannelResolveResult,
    MultiPlatformClient,
    MultiPlatformClientConfig,
    MultiPlatformKickChannelResolveRequest,
    MultiPlatformKickChatListenRequest,
    MultiPlatformKickSendMessageRequest,
    MultiPlatformKickChatStartResult,
    MultiPlatformKickVideoMetricsRequest,
    MultiPlatformSendMessageRequest,
    MultiPlatformTwitchChatListenRequest,
    MultiPlatformTwitchChatStartResult,
    MultiPlatformTwitchChannelResolveRequest,
    MultiPlatformVideosClient,
    MultiPlatformYoutubeChannelResolveRequest,
    MultiPlatformYoutubeChatListenRequest,
    MultiPlatformYoutubeSendMessageRequest,
    MultiPlatformYoutubeChatStartResult,
    MultiPlatformYoutubeVideoMetricsRequest,
} from "./multi-platform.js"
export type {
    ChannelMetric,
    ChannelMetrics,
    ChannelMetricsRequest,
    ChatErrorHandler,
    ChatEventHandler,
    ChatListener,
    ChatMessage,
    Platform as PlatformName,
    SendMessageResult,
    VideoMetric,
    VideoMetrics,
    VideoMetricsRequest,
} from "./types.js"
export type {
    ChatMessage as YoutubeChatMessage,
    YoutubeChannelResolveRequest,
    YoutubeChannelResolveResult,
    YoutubeChatClient,
    YoutubeChatListenRequest,
    YoutubeChatListener,
    YoutubeSendMessageRequest,
    YoutubeSendMessageResult,
    YoutubeChatStartResult,
    YoutubeChannelsClient,
    YoutubeChannelMetric,
    YoutubeClient,
    YoutubeClientConfig,
    YoutubeVideoMetric,
    YoutubeVideosClient,
} from "./providers/youtube/types.js"
export type {
    ChatMessage as KickChatMessage,
    KickChannelResolveRequest,
    KickChannelResolveResult,
    KickChannelsClient,
    KickChatClient,
    KickChatListenRequest,
    KickChatListener,
    KickChatStartResult,
    KickClient,
    KickClientConfig,
    KickEventSubscription,
    KickNodeWebhookRequest,
    KickSendBotMessageRequest,
    KickSendMessageRequest,
    KickSendMessageResult,
    KickSendMessageType,
    KickSendUserMessageRequest,
    KickStopOptions,
    KickSubscriptionMode,
    KickVideoMetric,
    KickVideosClient,
    KickWebhookRequest,
    KickWebhookResult,
} from "./providers/kick/types.js"
export type {
    ChatMessage as TwitchChatMessage,
    ChannelMetrics as TwitchChannelMetrics,
    ChannelMetricsRequest as TwitchChannelMetricsRequest,
    TwitchChatClient,
    TwitchChatListenRequest,
    TwitchChatListener,
    TwitchChatStartResult,
    TwitchChannelResolveRequest,
    TwitchChannelResolveResult,
    TwitchChannelMetric,
    TwitchChannelsClient,
    TwitchClient,
    TwitchClientConfig,
    TwitchEventSubscription,
    TwitchStopOptions,
} from "./providers/twitch/types.js"

/**
 * Runtime constants for callers who prefer enum-like values over string literals.
 */
export const Platform = Object.freeze({
    YouTube: "youtube",
    Twitch: "twitch",
    Kick: "kick",
} as const)
